require 'rubygems'
require 'nokogiri'
require 'active_support'

spec = ARGV[0] || "fidata/fi/*.xml"
generated = []

puts(<<-EOS)
# This is an autogenerated file. Do not make changes here. If you need to make changes
# to make a particular augoten fetcher work, create a new standalone fetcher, and then
# disable the autogen fetcher. Look at scottrade.rb for an example.
EOS

puts

Dir.glob(spec).each do |fn|
  #puts fn

  xml = File.read(fn)
  doc = Nokogiri::XML(xml)
  
  url = CGI.unescapeHTML(doc.search('ProviderURL').text)

  # skip if no url, or yodlee
  next if url.empty? || url =~ /DataFeedAPI/

  # capture details, setting strings that contain just whitespace to empty.
  fiorg = doc.search('Org').text.gsub(/\A\s+\Z/m,'')
  fid   = doc.search('FID').text.gsub(/\A\s+\Z/m,'')
  name  = doc.search('Name').text.gsub(/\A\s+\Z/m,'')
  udesc = doc.search('UserIDString').text.gsub(/\A\s+\Z/m,'').gsub('"', '\"')
  pdesc = doc.search('PasswordString').text.gsub(/\A\s+\Z/m,'').gsub('"', '\"')
  desc  = doc.search('CommentsTXT').text.gsub(/\A\s+\Z/m,'').gsub('"', '\"')


  brokerid = doc.search('BrokerID').text

  # capabilities
  c = {}
  c[:bank]   = doc.search('Bank').text.to_i
  c[:invest] = doc.search('BrkStmt').text.to_i
  c[:cc]     = doc.search('CreditCard').text.to_i


  c.each do |k,v|
    if v == 1
      class_name = "Autogen#{name.scan(/[0-9A-Za-z]*/).to_s.camelize}"
      #puts " generating #{class_name}"
      
      p = "#{k.to_s.capitalize}::#{class_name}"
      next if generated.include?(p)

      generated << p

      code = <<-EOS
# Generated from #{fn}:
class BankJob::#{p} < BankJob::Fetcher
  URL = "#{url}"

  needs :username, "#{udesc}"
  needs :password, "#{pdesc}"
  needs :account_number

  institution "#{name}"
  ofx_fid "#{fid}"
  description "#{desc}"

  def initialize(args)
    super

    @ofx_client = BankJob::OfxClient.new(
      :user     => username,
      :pass     => password,
      :fiorg    => "#{fiorg}",
      :fid      => self.class.ofx_fid, #{"\n      :brokerid => '#{brokerid}'," if k == :invest}
      :url      => URL)
  end

  def fetch
    @ofx_client.fetch(
      :type  => self.class.institution_type,
      :start => 90.days.ago,
      :acct  => account_number
    )
  end

  def list
    @ofx_client.list
  end
end unless BankJob.disabled?("#{p}")

      EOS

      puts code
      
    end
  end
end
